# Generated by Django 5.1.6 on 2025-03-06 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('railway', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='intermediatestation',
            options={'ordering': ['arrival_time']},
        ),
    ]
