# Generated by Django 5.0.6 on 2025-05-14 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('railway', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='intermediatestation',
            name='station_order',
            field=models.IntegerField(default=0),
        ),
    ]
