# Generated by Django 5.1.6 on 2025-03-12 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('railway', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainGraoh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_seats', models.IntegerField()),
                ('from_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departures', to='railway.intermediatestation')),
                ('to_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrivals', to='railway.intermediatestation')),
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edges', to='railway.train')),
            ],
            options={
                'unique_together': {('train', 'from_station', 'to_station')},
            },
        ),
    ]
