# Generated by Django 5.0.6 on 2025-02-27 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('railway', '0002_alter_customuser_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='train',
            name='running_days',
            field=models.ManyToManyField(related_name='trains', to='railway.day'),
        ),
    ]
