# Generated by Django 5.1.6 on 2025-03-06 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('railway', '0002_alter_intermediatestation_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='train',
            name='friday',
        ),
        migrations.RemoveField(
            model_name='train',
            name='monday',
        ),
        migrations.RemoveField(
            model_name='train',
            name='saturday',
        ),
        migrations.RemoveField(
            model_name='train',
            name='sunday',
        ),
        migrations.RemoveField(
            model_name='train',
            name='thursday',
        ),
        migrations.RemoveField(
            model_name='train',
            name='tuesday',
        ),
        migrations.RemoveField(
            model_name='train',
            name='wednesday',
        ),
        migrations.AddField(
            model_name='train',
            name='running_days',
            field=models.ManyToManyField(to='railway.day'),
        ),
    ]
