# Generated by Django 5.1.6 on 2025-02-27 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('railway', '0003_day_train_running_days'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='train',
            name='boarding_time',
        ),
        migrations.RemoveField(
            model_name='train',
            name='departure_time',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='intermediatestation',
            name='train',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='railway.train'),
        ),
        migrations.AlterField(
            model_name='train',
            name='destination',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='train',
            name='running_days',
            field=models.ManyToManyField(blank=True, to='railway.day'),
        ),
        migrations.AlterField(
            model_name='train',
            name='source',
            field=models.CharField(max_length=100),
        ),
    ]
