# Generated by Django 5.1.6 on 2025-02-28 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('railway', '0004_remove_train_boarding_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='train',
            name='operating_days_data',
            field=models.TextField(default='[]'),
        ),
    ]
