# Generated by Django 5.1.6 on 2025-02-28 12:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('railway', '0006_remove_train_running_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='train',
            name='boarding_time',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
        migrations.AddField(
            model_name='train',
            name='departure_time',
            field=models.TimeField(default=datetime.time(23, 59)),
        ),
    ]
