# Generated by Django 5.1.6 on 2025-03-02 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('railway', '0009_alter_intermediatestation_train'),
    ]

    operations = [
        migrations.AddField(
            model_name='intermediatestation',
            name='is_destination',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='intermediatestation',
            name='is_source',
            field=models.BooleanField(default=False),
        ),
    ]
